In [11]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive
%cd git_repos

Mounted at /content/drive
/content/drive/MyDrive
/content/drive/MyDrive/git_repos


In [12]:
!git clone https://github.com/Chee613/DS-Tuto.git

Cloning into 'DS-Tuto'...


In [36]:
!git config --global user.email "tankeat0613@gmail.com"
!git config --global user.name "Chee613"


In [15]:
%cd DS-Tuto

/content/drive/MyDrive/git_repos/DS-Tuto


In [16]:
!mv "../../Colab Notebooks/Tutorial03.ipynb" "./"

In [37]:
!git status

On branch main
Your branch is based on 'origin/main', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean


In [40]:
!git add Tutorial03.ipynb

In [41]:
!git commit -m "Add T3"

[main ebf4411] Add T3
 1 file changed, 1 insertion(+), 1 deletion(-)


In [42]:
!git push --force https://Chee613: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@github.com/Chee613/DS-Tuto.git main

remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/Chee613/DS-Tuto.git/'


In [52]:
!git add .
!git commit -m "Add Tuto3"
!git push https://Chee613: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@github.com/Chee613/DS-Tuto.git main

[main 8246ec3] Add Tuto3
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 2.10 KiB | 195.00 KiB/s, done.
Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
To https://github.com/Chee613/DS-Tuto.git
   909cb36..8246ec3  main -> main


In [43]:
import numpy as np
# 1. Create a numpy ar{ray of size 2 x 2
arr=np.array([[1,2],[3,4]])
print("2x2 Array: \n", arr)

2x2 Array: 
 [[1 2]
 [3 4]]


In [47]:
# 2. Create a random numpy array of size 3x4
randarr=np.random.randint(0,51,size=(3,4))
print("\n Random Array: \n",randarr)


 Random Array: 
 [[12 48 50 30]
 [43 36 43  2]
 [46 34 15 27]]


In [48]:
# 3. Create a numpy array of ones and a numpy array of zeroes
ones=np.ones((3,3))
zero=np.zeros((3,3))
print("\nArray of Ones: \n", ones)
print("\nArray of Zeros: \n",zero)


Array of Ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of Zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [49]:
# 4.Create a random numpy array of size 6x3 and transpose it
arr=np.random.randint(0,51,size=(6,3))
transpose_arr=arr.T
print("\nArray before transpose: \n",arr)
print("\nArray after transpose: \n",transpose_arr)


Array before transpose: 
 [[15 25 36]
 [ 8 29 14]
 [13 18  9]
 [38 31 29]
 [17 49 45]
 [36 27 34]]

Array after transpose: 
 [[15  8 13 38 17 36]
 [25 29 18 31 49 27]
 [36 14  9 29 45 34]]


In [50]:
#5. Create two random numpy arrays of size n x p and p x m and compute the dot product
n,p,m=2,3,4
A=np.random.rand(n,p)
B=np.random.rand(p,m)
dot_product=np.dot(A,B)
print("\nMatrix A (nxp):\n",A)
print("\nMatrix B (pxm):\n",B)
print("\n Dot product (nxm):\n",dot_product)


Matrix A (nxp):
 [[0.74460184 0.87965399 0.31527374]
 [0.01595339 0.1769537  0.22162305]]

Matrix B (pxm):
 [[0.49404416 0.010633   0.59969529 0.99221852]
 [0.72431473 0.20384092 0.75918101 0.96830598]
 [0.93199029 0.17192845 0.17929126 0.58814385]]

 Dot product (nxm):
 [[1.2988446  0.24143135 1.17087665 1.77600826]
 [0.34260238 0.07434334 0.18364214 0.31752081]]
